/**
 * SeizeLearn AI Service
 * Powered by Google Gemini API with seamless local heuristic fallback.
 * Allows interactive prompt scoring (C.T.C.O), live code debugging, and speech evaluation.
 */

const GEMINI_API_KEY = 
  import.meta.env.VITE_GEMINI_API_KEY || 
  import.meta.env.VITE_FIREBASE_API_KEY || 
  '';

export interface PromptEvaluationResult {
  score: number;
  feedback: string[];
  strengths: string[];
  improvements: string[];
  simulatedOutput: string;
  isLiveAI: boolean;
}

export interface CodeReviewResult {
  summary: string;
  strengths: string[];
  suggestions: string[];
  fixedCodeSnippet?: string;
  isLiveAI: boolean;
}

export interface SpeechEvaluationResult {
  score: number;
  paceRating: 'Too fast' | 'Optimal pace' | 'Too slow';
  feedback: string[];
  refinedVersion: string;
  isLiveAI: boolean;
}

/**
 * Call Gemini REST API securely with structured JSON instruction
 */
async function callGemini(systemPrompt: string, userContent: string): Promise<string | null> {
  if (!GEMINI_API_KEY) return null;

  try {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${encodeURIComponent(GEMINI_API_KEY)}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: `${systemPrompt}\n\nUser Input:\n${userContent}` }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.4,
          maxOutputTokens: 1024
        }
      })
    });

    if (!response.ok) {
      console.warn(`Gemini API returned ${response.status}: using intelligent fallback mode.`);
      return null;
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    return candidateText || null;
  } catch (err) {
    console.warn('Gemini API call failed (using fallback evaluation):', err);
    return null;
  }
}

/**
 * 1. Evaluate prompt according to C.T.C.O framework (Context, Task, Constraints, Output)
 */
export async function evaluatePromptCTCO(promptText: string): Promise<PromptEvaluationResult> {
  const systemPrompt = `You are an expert AI prompt engineering instructor. 
Evaluate the user's prompt strictly based on the C.T.C.O framework:
- Context: Did they provide role, background, or domain context?
- Task: Is the core objective crystal clear?
- Constraints: Are there limits, length restrictions, or rules?
- Output format: Did they specify formatting (e.g. Markdown, table, JSON)?

Respond in valid JSON format only, matching this structure without markdown formatting or code fences:
{
  "score": number between 40 and 100,
  "feedback": ["point 1", "point 2"],
  "strengths": ["strength 1", "strength 2"],
  "improvements": ["improvement 1", "improvement 2"],
  "simulatedOutput": "A realistic sample output generated by this prompt"
}`;

  const geminiResponse = await callGemini(systemPrompt, promptText);

  if (geminiResponse) {
    try {
      // Clean JSON if fences exist
      const cleaned = geminiResponse.replace(/```json/gi, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleaned);
      return {
        score: typeof parsed.score === 'number' ? parsed.score : 85,
        feedback: Array.isArray(parsed.feedback) ? parsed.feedback : ['Prompt meets core criteria.'],
        strengths: Array.isArray(parsed.strengths) ? parsed.strengths : ['Clear objective specified.'],
        improvements: Array.isArray(parsed.improvements) ? parsed.improvements : ['Consider specifying output length.'],
        simulatedOutput: parsed.simulatedOutput || 'Sample generated response matching your prompt.',
        isLiveAI: true
      };
    } catch {
      // JSON parse error, proceed to heuristic
    }
  }

  // Heuristic rule-based fallback
  const lower = promptText.toLowerCase();
  const hasContext = /(you are|act as|context|role|background|as a|assume)/.test(lower);
  const hasTask = /(explain|build|write|create|generate|summarize|list|design|implement|analyze)/.test(lower);
  const hasConstraints = /(do not|limit|maximum|concise|within|only|avoid|keep it|strictly)/.test(lower);
  const hasOutput = /(markdown|table|bullet|json|paragraph|summary|format|code block)/.test(lower);

  let score = 40;
  const feedback: string[] = [];
  const strengths: string[] = [];
  const improvements: string[] = [];

  if (hasContext) {
    score += 15;
    strengths.push('Context & Persona: Clearly defines the persona or domain context.');
  } else {
    improvements.push('Add Context: Define who the AI is acting as (e.g., "Act as a Senior React Engineer").');
  }

  if (hasTask) {
    score += 15;
    strengths.push('Task Clarity: Uses an actionable verb with a specific primary goal.');
  } else {
    improvements.push('Clarify Task: Use a direct action verb (e.g., "Explain step-by-step" or "Compare X and Y").');
  }

  if (hasConstraints) {
    score += 15;
    strengths.push('Constraints: Defines boundaries, preventing hallucinations and verbosity.');
  } else {
    improvements.push('Add Constraints: Include restrictions (e.g., "Under 150 words" or "No complex jargon").');
  }

  if (hasOutput) {
    score += 15;
    strengths.push('Output Specification: Explicitly declares desired format.');
  } else {
    improvements.push('Specify Output Format: Tell the AI how to format its response (e.g., "Format as Markdown bullet points").');
  }

  feedback.push(`C.T.C.O Score: ${score}/100.`);
  if (score >= 80) {
    feedback.push('Excellent prompt structure! Ready for professional engineering workflows.');
  } else {
    feedback.push('Add missing components to achieve higher accuracy and reduce follow-up iterations.');
  }

  const simulatedOutput = `### AI Response Preview\n\nOptimistic UI updates immediately reflect changes in the interface before the server confirms the operation—just like a coffee shop handing you a buzzer immediately while they prepare your drink.\n\nIn React 19, the \`useOptimistic\` hook makes this seamless. You display the anticipated state right away, and if the network call fails, React gracefully reverts the UI back to the true state without messy manual rollback logic.`;

  return {
    score,
    feedback,
    strengths,
    improvements,
    simulatedOutput,
    isLiveAI: false
  };
}

/**
 * 2. Explain or debug code in Web CodeLab
 */
export async function explainOrDebugCode(
  html: string, 
  css: string, 
  js: string, 
  userQuery?: string
): Promise<CodeReviewResult> {
  const systemPrompt = `You are an expert web development tutor.
Analyze this learner's HTML, CSS, and JavaScript. Provide:
1. A concise 2-sentence summary of what the code achieves.
2. 2-3 key strengths.
3. 2-3 actionable suggestions for performance, accessibility, or modern best practices.
Respond in valid JSON without markdown wrapping:
{
  "summary": "...",
  "strengths": ["...", "..."],
  "suggestions": ["...", "..."],
  "fixedCodeSnippet": "optional improved snippet"
}`;

  const payload = `HTML:\n${html}\n\nCSS:\n${css}\n\nJS:\n${js}\n\nUser Question:\n${userQuery || 'Please review my code.'}`;
  const geminiResponse = await callGemini(systemPrompt, payload);

  if (geminiResponse) {
    try {
      const cleaned = geminiResponse.replace(/```json/gi, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleaned);
      return {
        summary: parsed.summary || 'Code reviewed successfully.',
        strengths: Array.isArray(parsed.strengths) ? parsed.strengths : ['Clean structure and readable selectors.'],
        suggestions: Array.isArray(parsed.suggestions) ? parsed.suggestions : ['Consider adding ARIA labels for buttons.'],
        fixedCodeSnippet: parsed.fixedCodeSnippet,
        isLiveAI: true
      };
    } catch {
      // Fallback
    }
  }

  // Heuristic review
  const strengths: string[] = [];
  const suggestions: string[] = [];

  if (html.includes('class="') || html.includes("class='")) {
    strengths.push('Semantic class names used for predictable styling.');
  }
  if (css.includes('display: flex') || css.includes('display: grid')) {
    strengths.push('Modern layout system (Flexbox/Grid) leveraged effectively.');
  }
  if (js.includes('addEventListener') || js.includes('.onclick')) {
    strengths.push('Interactive event listeners attached for dynamic user feedback.');
  }

  if (!html.includes('aria-') && html.includes('<button')) {
    suggestions.push('Add `aria-label` to interactive buttons to improve screen reader accessibility.');
  }
  if (!css.includes('transition') && css.includes(':hover')) {
    suggestions.push('Add `transition: all 0.2s ease` to smooth out hover states.');
  }
  if (suggestions.length === 0) {
    suggestions.push('Consider extracting reusable CSS variables for consistent color palettes.');
  }

  return {
    summary: 'The code demonstrates solid understanding of DOM manipulation, component composition, and responsive CSS.',
    strengths: strengths.length > 0 ? strengths : ['Code parses cleanly without critical syntax errors.'],
    suggestions,
    isLiveAI: false
  };
}

/**
 * 3. Evaluate elevator pitch or speech practice transcript
 */
export async function evaluateSpeechOrInterview(
  transcript: string, 
  targetPitch: string
): Promise<SpeechEvaluationResult> {
  const systemPrompt = `You are an executive communication coach.
Analyze the user's speech transcript against the target pitch.
Rate their delivery, clarity, structure, and professional tone.
Respond strictly in JSON:
{
  "score": number between 50 and 100,
  "paceRating": "Optimal pace" or "Too fast" or "Too slow",
  "feedback": ["...", "..."],
  "refinedVersion": "Refined professional sentence"
}`;

  const payload = `Target Pitch:\n${targetPitch}\n\nSpoken Transcript:\n${transcript}`;
  const geminiResponse = await callGemini(systemPrompt, payload);

  if (geminiResponse) {
    try {
      const cleaned = geminiResponse.replace(/```json/gi, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleaned);
      return {
        score: typeof parsed.score === 'number' ? parsed.score : 85,
        paceRating: parsed.paceRating || 'Optimal pace',
        feedback: Array.isArray(parsed.feedback) ? parsed.feedback : ['Clear delivery and articulate phrasing.'],
        refinedVersion: parsed.refinedVersion || targetPitch,
        isLiveAI: true
      };
    } catch {
      // Fallback
    }
  }

  const wordCount = transcript.trim().split(/\s+/).filter(Boolean).length;
  let score = 75;
  const feedback: string[] = [];

  if (wordCount > 25) {
    score += 15;
    feedback.push('Solid elaboration and complete sentence structure.');
  } else if (wordCount > 10) {
    score += 5;
    feedback.push('Concise answer, but could expand on practical examples.');
  } else {
    score = 60;
    feedback.push('Answer is very brief; practice speaking in 2-3 structured sentences.');
  }

  const fillerRegex = /\b(um|uh|like|you know|basically|actually)\b/gi;
  const fillers = (transcript.match(fillerRegex) || []).length;
  if (fillers === 0 && wordCount > 10) {
    score += 10;
    feedback.push('Zero filler words detected! Confident and poised delivery.');
  } else if (fillers > 0) {
    feedback.push(`Detected ${fillers} filler word(s). Try pausing for a breath instead of saying "um" or "like".`);
  }

  score = Math.min(100, Math.max(50, score));

  return {
    score,
    paceRating: wordCount > 50 ? 'Too fast' : wordCount < 15 ? 'Too slow' : 'Optimal pace',
    feedback,
    refinedVersion: `During my intensive training at SeizeLearn, I engineered full-stack applications with React and Firebase, reducing manual workflows and proving production readiness through end-to-end deliverables.`,
    isLiveAI: false
  };
}
